# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foguetinho' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foguetinho
  pod 'Google-Mobile-Ads-SDK'
  target 'FoguetinhoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoguetinhoUITests' do
    # Pods for testing
  end

end
