# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foguetinho no espaço' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foguetinho no espaço
	pod 'Google-Mobile-Ads-SDK'

  target 'Foguetinho no espaçoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Foguetinho no espaçoUITests' do
    # Pods for testing
  end

end
